
create table EMPLOYEES (
ID NUMBER(4) primary key,
FIRST_NAME VARCHAR2(25),
LAST_NAME VARCHAR2(25),
MobileNo NUMBER(8),
SALARY NUMBER(9,2)
);

CREATE SEQUENCE emp_seq START WITH 1;

CREATE OR REPLACE TRIGGER emp_bir 
BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW

BEGIN
  SELECT emp_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;

--DROP TRIGGER emp_bir; 

CREATE OR REPLACE PROCEDURE sp_getEmpById 
   (EMP_ID IN NUMBER, FIRST_NAME OUT VARCHAR2, LAST_NAME OUT VARCHAR2, MobileNo OUT NUMBER, SALARY OUT NUMBER) AS
BEGIN
   SELECT FIRST_NAME, LAST_NAME, MobileNo, SALARY INTO FIRST_NAME, LAST_NAME, MobileNo, SALARY
   FROM EMPLOYEE
   WHERE ID = EMP_ID;
END;

CREATE OR REPLACE PROCEDURE sp_addEmp 
   (EMP_FIRST_NAME IN VARCHAR2, EMP_LAST_NAME IN VARCHAR2, EMP_MobileNo IN NUMBER, EMP_SALARY IN NUMBER) AS
BEGIN
   INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,MobileNo,SALARY) VALUES (EMP_FIRST_NAME,EMP_LAST_NAME,EMP_MobileNo,EMP_SALARY);
END;

CREATE OR REPLACE PROCEDURE sp_updateEmp 
   (EMP_ID IN NUMBER, EMP_FIRST_NAME IN VARCHAR2, EMP_LAST_NAME IN VARCHAR2, EMP_MobileNo IN NUMBER, EMP_SALARY IN NUMBER) AS
BEGIN
   UPDATE EMPLOYEE SET FIRST_NAME = EMP_FIRST_NAME,LAST_NAME = EMP_LAST_NAME,MobileNo = EMP_MobileNo,SALARY = EMP_SALARY WHERE ID = EMP_ID;
END;

CREATE OR REPLACE PROCEDURE sp_deleteEmp 
   (EMP_ID IN NUMBER) AS
BEGIN
   DELETE FROM EMPLOYEE WHERE ID = EMP_ID;
END;

--DROP PROCEDURE sp_name;

select * from employee;
alter table employee read write;
