
create table EMPLOYEES (
ID NUMBER(4) primary key,
FIRST_NAME VARCHAR2(25),
LAST_NAME VARCHAR2(25),
MobileNo NUMBER(8),
SALARY NUMBER(9,2)
);

CREATE SEQUENCE emp_seq START WITH 1;

CREATE OR REPLACE TRIGGER emp_bir 
BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW

BEGIN
  SELECT emp_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;

--DROP TRIGGER emp_bir; 

CREATE OR REPLACE PROCEDURE getEmpDetails 
   (EMP_ID IN NUMBER, FIRST_NAME OUT VARCHAR2, LAST_NAME OUT VARCHAR2, MobileNo OUT NUMBER, SALARY OUT NUMBER) AS
BEGIN
   SELECT FIRST_NAME, LAST_NAME, MobileNo, SALARY INTO FIRST_NAME, LAST_NAME, MobileNo, SALARY
   FROM EMPLOYEE
   WHERE ID = EMP_ID;
END;

--DROP PROCEDURE getEmpDetails;

insert into employee (FIRST_NAME,LAST_NAME,MobileNo,SALARY) values('Moayad','AL-Falahi',96430801,123.12);
select * from employee;
alter table employee read write;

/*var FIRST_NAME VARCHAR2;
var LAST_NAME VARCHAR2(25);
var MobileNo NUMBER(8);
var SALARY NUMBER(9,2);
EXECUTE getEmpDetails(1,FIRST_NAME,LAST_NAME,MobileNo,SALARY);*/
